    hooks:
        -   id: prepare-commit-msg
            entry: ./config/git/prepare-commit-msg
            name: Prepare commit messages
            description: Prepare commit messages
            language: script