#!/bin/sh
DEVELOP_BRANCH="master/NO-TASK";
BRANCH_NAME=$(git symbolic-ref --short HEAD)
TASK_NAME="${BRANCH_NAME##*/}"

if [ "master" = "$BRANCH_NAME" ]; then 
    TASK_NAME="${DEVELOP_BRANCH##*/}"
fi

BRANCH_IN_COMMIT=$(grep -c "\[$TASK_NAME\]" $1)

if [ -n "$TASK_NAME" ] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then 
  sed -i.bak -e "1s/^/$TASK_NAME: /" $1
fi
